#page title
page_title                                : Summoning Stone                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6443965587                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : http://appstore.com/summoningstone                                         # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Summoning Stone                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The Soundtrack to Your Adventure

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Beau Nouvelle
your_link                                 : https://iosdev.space/@beau
your_city                                 : Melbourne
email_address                             : hello@summoningstone.app
#facebook_username                         :
#instagram_username                        : ebaehr
twitter_username                          : beaunouvelle
#github_username                           : emilbaehr
#youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
    
  - title                                 : Integrated with Apple Music
    description                           : Integrate seamlessly with Apple Music and access all your playlists to create immersive soundscapes.
    fontawesome_icon_name                 : link

  - title                                 : Sounds for Every Scene
    description                           : Packed with sound effects for both sci-fi and fantasy style games, the soundboard adds depth to your scenes.
    fontawesome_icon_name                 : volume-up

  - title                                 : Amazing Visuals
    description                           : Display stunning artwork on your TV with weather effects to fully immerse your players.
    fontawesome_icon_name                 : eye

  - title                                 : Simple Sound Categorization
    description                           : Organize your sounds into "scenes" and categorize by campaign for easy access.
    fontawesome_icon_name                 : table
  
  - title                                 : Scene-Building Soundscapes
    description                           : Select a scene and bring it to life with music, ambience, and SFX all blended together.
    fontawesome_icon_name                 : flask

  - title                                 : Unforgettable RPG Experiences
    description                           : Captivate your players, transport them to a world beyond their imagination, and create unforgettable gaming experiences.
    fontawesome_icon_name                 : star


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.3

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#9102FE"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#bbbbbb"

feature_icons_foreground_color            : "#9102FE"
feature_icons_background_color            : "#222222"

social_icons_foreground_color             : "#9102FE"
social_icons_background_color             : "#222222"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
