#page title
page_title                                : Summoning Stone - The best Tabletop RPG companion app for Music, Ambience and Sound Effects                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6443965587                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/apple-store/id6443965587?pt=123648022&ct=website&mt=8                                       # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://impresskit.net/87243e36-7f9b-4ace-91e3-28550f9585ec                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Summoning Stone                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Filled to the brim with all the audio tools you will ever need to guide your players through epic adventures!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name                                 : Beau Nouvelle
your_link                                 : https://discord.gg/R7mCUNJ4FJ
your_city                                 : Melbourne
email_address                             : hello@summoningstone.app
#facebook_username                         :
#instagram_username                        : ebaehr
#twitter_username                          : beaunouvelle
#github_username                           : emilbaehr
youtube_username                          : GetSwifty



# Feature List                            Edit, add or remove features to be presented.
features                                  :
    
  - title                                 : Integrated with Music
    description                           : Integrate seamlessly with Apple Music and access all your playlists and millions of tracks from your favorite movies and videos games to create immersive soundscapes.
    fontawesome_icon_name                 : link

  - title                                 : Sounds for Every Scene
    description                           : Packed with sound effects for fantasy, modern and sci-fi tabletop games, the soundboard adds depth to your scenes.
    fontawesome_icon_name                 : volume-up

  - title                                 : Amazing Visuals
    description                           : Display stunning artwork or maps on your TV with weather effects to fully immerse your players. These change automatically when your players switch scenes.
    fontawesome_icon_name                 : map

  - title                                 : Control Your Domain
    description                           : Got some smart lights or other automated devices in your gaming space? Hook them up to Summoning Stone using the Siri Shortcuts integration and make your RPG a 4D experience.
    fontawesome_icon_name                 : lightbulb

  - title                                 : Simple Sound Categorization
    description                           : Create "scenes" comprising of music, sound effects and ambience. Attach these to a Campaign and crossfade between them with the press of a button.
    fontawesome_icon_name                 : table
  
  - title                                 : Scene-Building Soundscapes
    description                           : Select a scene and bring it to life with music, ambience, and SFX all blended together.
    fontawesome_icon_name                 : flask

  - title                                 : Steam Safe Music
    description                           : Not only does Summoning Stone work with Apple music, but it also has some epic royalty free music of it's own!
    fontawesome_icon_name                 : star

  - title                                 : Unforgettable RPG Experiences
    description                           : Captivate your players, transport them to a world beyond their imagination, and create unforgettable gaming experiences using the best sound effects, ambient music from any tabletop rpg app on the platform.
    fontawesome_icon_name                 : brain

  - title                                 : What can I play?
    description                           : Summoning Stone is built for all tabletop and board games. Dungeons and Dragons, Pathfinder, Starfinder, Vampire the Masquerade, The One Ring, Warhammer, Talisman, Magic the Gathering, Gloomhaven, Hero Quest...
    fontawesome_icon_name                 : dice


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.3

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#9102FE"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#bbbbbb"

feature_icons_foreground_color            : "#9102FE"
feature_icons_background_color            : "#222222"

social_icons_foreground_color             : "#9102FE"
social_icons_background_color             : "#222222"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
